version: 2
updates:
- package-ecosystem: pip
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: qrcodegen
    versions:
    - "> 1.2.0"
  - dependency-name: misaka
    versions:
    - ">= 2.a"
    - "< 3"
