language: python
# Run on Travis CI's docker infrastructure
sudo: false

matrix:
  include:
    - python: 2.7
    - python: 3.5

env:
  global:
    - PIP_WHEEL_DIR=$HOME/.cache/pip/wheels
    - PIP_FIND_LINKS=file://$HOME/.cache/pip/wheels

cache:
  directories:
    - ~/.cache/pip

addons:
    postgresql: "9.4"

services:
    - memcached
    - postgresql

before_install:
    - mkdir -p ~/.cache/pip/wheels
    - pip install -U pip setuptools pbr
    - pip --version
    - export VE=$VIRTUAL_ENV  # Use the virtual environment travis provides.
    - cp etc/pip.conf $VE

install:
    - npm install -g gulp
    - createdb -E UTF8 -O travis weasyl_test
    - ./.travis-install.sh

script:
    - ./.travis-test.sh

after_success:
    - codecov
