language: python
dist: bionic

matrix:
    include:
        - python: 2.7
        - python: 3.5

env:
    global:
        - PIP_WHEEL_DIR=$HOME/.cache/pip/wheels
        - PIP_FIND_LINKS=file://$HOME/.cache/pip/wheels

cache:
    directories:
        - ~/.cache/pip

addons:
    apt:
        packages:
            - sassc
    postgresql: "9.6"

services:
    - memcached
    - postgresql

before_install:
    - mkdir -p ~/.cache/pip/wheels ~/.bin
    - pip install -U pip setuptools pbr
    - pip --version
    - export VE=$VIRTUAL_ENV  # Use the virtual environment travis provides.
    - nvm install 13

install:
    - createdb -E UTF8 -O travis weasyl_test
    - ./.travis-install.sh

script:
    - ./.travis-test.sh

after_success:
    - codecov
